Fix TRUNCATE could remove shared AO hash entry in use by other transactions.
An example repro is:

-- session1, under testdb1:

testdb1=# create table aorow(a int) with (appendonly=true);
testdb1=# insert into aorow select generate_series(1,10);
testdb1=# create database testdb2 with template testdb1;
testdb1=# insert into aorow select * from aorow;
testdb1=# \watch 1
...
-- session2, under testdb2:

testdb2=# truncate aorow;

-- session1:
ERROR:  expected an AO hash entry for relid 16385 but found none (appendonlywriter.c:419)

The root cause is CREATE DATABASE WITH TEMPLATE clause clones testdb1 objects and shares
the same AO hash entry identified by relid only between both databases. So once the entry
is removed by TRUNCATE in testdb2, later lookup of the shared hash entry in testdb1 would
be failed.

The solution is to check the shared AO hash entry under lookup and won't remove if it is
in use by other transactions.